### ISSUE TITLE
Plugin not working when site_url not defined

### ISSUE THREAD

**Issue by lkavicky** [fcannizzaro/mkdocs-sequence-js-plugin#1]
I'm making a file-based documentation (meaning will not be deployed to a web server) and would like to incorporate sequence.js diagrams. However, when not defining `site_url` in `mkdocs.yml` (because there will be no site), the plugin raises an error during documentaion building:

```
$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: D:\xyz\site
ERROR   -  Error building page 'writing-docs.md': string index out of range
Traceback (most recent call last):
  File "c:\users\luke\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 295, in build
    _build_page(file.page, config, files, nav, env, dirty)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\commands\build.py", line 220, in _build_page
    'post_page', output, page=page, config=config
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs_sequence_js_plugin\plugin.py", line 53, in on_post_page
    return append_dependencies(append_script(html, make_script(self.js[page.url])), self.config['popup'], config.get('site_url', ''))
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs_sequence_js_plugin\util.py", line 19, in append_dependencies
    site_url = site_url[:-1] if site_url[-1] == '/' else site_url
IndexError: string index out of range
```

**Comment by fcannizzaro** [comment]
fixed with 2e46ddcdb93da9d245e0cb0083d82592afac28a1
