### ISSUE TITLE
Plugin not compatible with mkdocs 1.1

### ISSUE THREAD

**Issue by lkavicky** [fcannizzaro/mkdocs-sequence-js-plugin#2]
After upgrade to mkdocs 1.1, plugin stopped working:

```
$ mkdocs build
Traceback (most recent call last):
  File "c:\users\luke\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Luke\AppData\Local\Programs\Python\Python37\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\config\base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\config\base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\config\base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\config\config_options.py", line 130, in validate
    return self.run_validation(value)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\config\config_options.py", line 591, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\config\config_options.py", line 599, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    return self.resolve()
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs_sequence_js_plugin\plugin.py", line 8, in <module>
    from mkdocs.utils import string_types
ImportError: cannot import name 'string_types' from 'mkdocs.utils' (c:\users\luke\appdata\local\programs\python\python37\lib\site-packages\mkdocs\utils\__init__.py)
```

**Comment by fcannizzaro** [comment]
fixed with 2e46ddcdb93da9d245e0cb0083d82592afac28a1
